get http://scores-shxw.onrender.com/scores

###

get https://scores-shxw.onrender.com/scores/1

###

delete http://scores-shxw.onrender.com/scores/2

###

post http://scores-shxw.onrender.com/scores
content-type: application/json

{ "name": "Pimu", "points": 33 }

###

get http://scores-shxw.onrender.com/scores?limit=10

###

get http://scores-shxw.onrender.com/scores?sort=asc

###

get http://scores-shxw.onrender.com/scores?sort=desc

###

get http://scores-shxw.onrender.com/scores?sort=desc&limit=10&pw=secret

