get https://scores-shxw.onrender.com/scores

###

get https://scores-shxw.onrender.com/scores/1

###

delete https://scores-shxw.onrender.com/scores/4

###

post https://scores-shxw.onrender.com/scores
content-type: application/json

{ "name": "Jonna", "points": 4 }

###

get http://scores-shxw.onrender.com/scores?limit=2

###

get http://scores-shxw.onrender.com/scores?sort=asc

###

get http://127.0.0.1:5000/scores?sort=desc

###

get http://127.0.0.1:5000/scores?sort=asc&limit=2

