get https://scores-shxw.onrender.com/scores

###

get https://scores-shxw.onrender.com/scores/2

###

delete https://scores-shxw.onrender.com/scores/2

###

post https://scores-shxw.onrender.com/scores
content-type: application/json

{ "name": "Sofia", "rating": 5678 }

